name: Markdown Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Markdown linter
        uses: docker://ghcr.io/github/super-linter:v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_MARKDOWN: true
          FILTER_REGEX_EXCLUDE: '(.github/workflows|node_modules|vendor)'
